version: 0.2

batch:
  build-fanout:
    parallelism: 2
    
phases:
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - npm install jest-junit --save-dev
      - |
        codebuild-tests-run \
         --test-command 'npx jest --runInBand --coverage' \
         --files-search "codebuild-glob-search '**/_tests_/**/*.test.js'" \
         --sharding-strategy 'equal-distribution'

  post_build:
    commands:
      - echo "Running post-build steps..."
      - echo "Build completed on `date`"

reports:
  my-reports:
    files:
      - '**/*.xml'               
    base-directory: .
    discard-paths: yes           
    file-format: JUNITXML   

