version: 0.2

phases:
  install:
    commands:
      - npm install jest-junit --save-dev
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo "Running codebuild-tests-run command without using CODEBUILD_CURRENT_SHARD_FILES"
      - npx jest --runInBand --coverage
         
  post_build:
    commands:
      - echo "Running post-build steps..."
      - echo "Build completed on `date`"

reports:
  test-reports:
    files:
      - '**/junit.xml'               
    base-directory: .
    discard-paths: yes           
    file-format: JUNITXML 
