version: 0.2

phases:
  install:
    commands:
      - npm install jest-junit --save-dev
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo "Running codebuild-tests-run command without using CODEBUILD_CURRENT_SHARD_FILES"
      - |
        codebuild-tests-run \
         --test-command 'npx jest --runInBand --coverage' \
      - echo "Running codebuild-tests-run command using CODEBUILD_CURRENT_SHARD_FILES"
      - codebuild-tests-run --test-command 'npx jest $(echo "$CODEBUILD_CURRENT_SHARD_FILES" | tr "\n" " ") --runInBand --coverage' --files-search "codebuild-glob-search '**/_tests_/**/*.test.js'" --sharding-strategy 'equal-distribution'
         
  post_build:
    commands:
      - echo "Running post-build steps..."
      - echo "Build completed on `date`"

reports:
  test-reports:
    files:
      - '**/junit.xml'               
    base-directory: .
    discard-paths: yes           
    file-format: JUNITXML 
