version: 0.2

batch:
  build-fanout:
    parallelism: 2
    
phases:
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - npm install jest-junit --save-dev
      - codebuild-tests-run --test-command 'echo "$CODEBUILD_CURRENT_SHARD_FILES" | sed -z "s/\n/,/g;s/,$//"' --files-search "codebuild-glob-search '_tests_/*test*'" --sharding-strategy 'equal-distribution'
      - codebuild-tests-run --test-command 'npx jest $(echo "$CODEBUILD_CURRENT_SHARD_FILES" | sed -z "s/\n/,/g;s/,$//") --runInBand --coverage' --files-search "codebuild-glob-search '_tests_/*test*'" --sharding-strategy 'equal-distribution'
  post_build:
    commands:
      - echo "Would deploy here"
