version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Adjust this to match your project's Node.js version
    commands:
      - echo "Debugging environment"
      - pwd
      - ls -la
      - echo "Node version: $(node --version)"
      - echo "NPM version: $(npm --version)"
      - npm config set prefix /usr/local
      - npm install -g npm@latest
      - npm cache clean --force
      - npm install
      - npm install jest-junit --save-dev
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo "running tests"
      - npx jest --ci --runInBand
  post_build:
    commands:
      - echo "Running post-build steps..."
      - echo "Build completed on $(date)"

reports:
  test-reports:
    files:
      - '**/junit.xml'
    base-directory: .
    discard-paths: yes
    file-format: JUNITXML
